CANDIDATE_LABELS = [
    "education", "politics", "health", "technology", "environment", "finance", "business","art", "entertainment", "sports",
    # "fashion", "food", "music", "film", "literature", "science",
    # "history", "philosophy", "religion", "travel", "architecture", "automobile", "aviation",
    # "space", "astronomy", "biology", "chemistry", "physics", "mathematics", "psychology",
    # "sociology", "anthropology", "economics", "marketing", "management", "leadership", "engineering",
    # "computer science", "programming", "software", "hardware", "networks", "cybersecurity",
    # "data science", "machine learning", "artificial intelligence", "robotics", "medicine",
    # "psychiatry", "neuroscience", "dentistry", "nursing", "veterinary", "pharmacy", "surgery",
    # "pediatrics", "oncology", "dermatology", "allergy", "gastroenterology", "cardiology", "diabetes",
    # "nutrition", "fitness", "yoga", "wellness", "weight loss", "mental health", "climate change",
    # "sustainability", "conservation", "renewable energy", "wildlife", "biodiversity", "ecology",
    # "geology", "geography", "meteorology", "oceanography", "urban planning", "agriculture",
    # "forestry", "fishing", "manufacturing", "retail", "e-commerce", "supply chain", "logistics",
    # "startups", "entrepreneurship", "venture capital", "stock market", "cryptocurrency", "blockchain",
    # "real estate", "insurance", "taxation", "banking", "investment", "economy", "globalization",
    # "employment", "unemployment", "inequality", "poverty", "social justice", "human rights",
    # "equality", "diversity", "inclusion", "racism", "sexism", "discrimination", "immigration",
    # "nationalism", "global politics", "diplomacy", "war", "peace", "humanitarianism", "activism",
    # "protest", "social media", "influencers", "content creation", "gaming", "virtual reality",
    # "augmented reality", "e-learning", "online education", "distance learning", "virtual events",
    # "telecommunication", "internet of things", "smart devices", "digital transformation",
    # "augmented intelligence", "automation", "robotic process automation", "big data",
    # "cloud computing", "cyber-physical systems", "quantum computing", "nanotechnology",
    # "bioinformatics", "biotechnology", "genetics", "bioengineering", "biochemistry", "virology",
    # "epidemiology", "public health", "healthcare policy", "alternative medicine", "physical therapy",
    # "alternative energy", "sustainable development", "waste management", "green technology",
    # "natural resources", "conservation biology", "environmental policy", "wildlife conservation",
    # "marine biology", "earth sciences", "climate policy", "renewable resources", "agricultural science",
    # "agroecology", "rural development", "manufacturing technology", "product design", "industrial engineering",
    # "retail management", "consumer behavior", "digital marketing", "brand management", "financial planning",
    # "macroeconomics", "microeconomics", "international trade", "monetary policy", "financial markets",
    # "business ethics", "corporate governance", "organizational behavior", "supply chain management",
    # "logistics management", "international business", "business strategy", "competitive analysis",
    # "entrepreneurial finance", "venture capital financing", "financial accounting", "management accounting",
    # "financial analysis", "investment banking", "financial modeling", "behavioral economics",
    # "developmental psychology", "cognitive psychology", "social psychology", "personality psychology",
    # "neuropsychology", "industrial-organizational psychology", "clinical psychology", "forensic psychology",
    # "counseling psychology", "school psychology", "sports psychology", "environmental psychology",
    # "educational psychology", "political philosophy", "ethics", "aesthetics", "metaphysics",
    # "epistemology", "logic", "social philosophy", "feminist philosophy", "philosophy of mind",
    # "philosophy of language", "philosophy of science", "bioethics", "applied ethics", "religious studies",
    # "comparative religion", "theology", "mythology", "ancient history", "medieval history", "renaissance",
    # "modern history", "contemporary history", "world history", "historiography", "historical archaeology",
    # "linguistics", "semantics", "syntax", "pragmatics", "phonetics", "phonology", "morphology", "language acquisition"
]